// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHQQAHVsmTigvApKdwCjXi4lPxzPTA_BY',
    appId: '1:180321028190:web:9975aa15ff452894170ccf',
    messagingSenderId: '180321028190',
    projectId: 'smartlearn-103e0',
    authDomain: 'smartlearn-103e0.firebaseapp.com',
    storageBucket: 'smartlearn-103e0.appspot.com',
    measurementId: 'G-7QQKCNCS8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9uy5LM8mrYAP_FFd1Ev4-43xYgZKGS_o',
    appId: '1:180321028190:android:3231c5e00773c1e5170ccf',
    messagingSenderId: '180321028190',
    projectId: 'smartlearn-103e0',
    storageBucket: 'smartlearn-103e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNCBz2xxSnR8ebc1sGzsFxt7mvv8EQWXU',
    appId: '1:180321028190:ios:f7a004f1d2ed7d1e170ccf',
    messagingSenderId: '180321028190',
    projectId: 'smartlearn-103e0',
    storageBucket: 'smartlearn-103e0.appspot.com',
    iosBundleId: 'com.example.theProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNCBz2xxSnR8ebc1sGzsFxt7mvv8EQWXU',
    appId: '1:180321028190:ios:144aed019d8e4858170ccf',
    messagingSenderId: '180321028190',
    projectId: 'smartlearn-103e0',
    storageBucket: 'smartlearn-103e0.appspot.com',
    iosBundleId: 'com.example.theProject.RunnerTests',
  );
}
